name: Gererate Datas

on:
  schedule: # execute every 12 hours
  - cron: "* */12 * * *"
  workflow_dispatch:
  
jobs:
  build:
      name: Jobs to update datas
      runs-on: ubuntu-latest
      steps:
        #Snake animation
        - uses: Platane/snk@master
          id: snake-gif
          with:
            github_user_name: thalita_ribeiro
            svg_out_path: dist/github-contribution-grid-snake.svg
            
        - uses: crazy-max/ghaction-github-pages@v2.1.3
          with:
            target_branch: output
            build_dir: dist
          env:
            GITHUB_TOKEN: ${{secret.GITHUB_TOKEN}}
